// src/components/Footer/Footer.vue
<template>
  <footer>
      <a
        href="https://loki87by.github.io/portfolio/"
        rel="noopener noreferrer"
        target="_blank"
      >
        &copy; 2022 Алексей Акулич
      </a>
    </footer>
</template>

<script>

export default {
  name: 'Footer'
}
</script>

<style>
@import url("../../styles/footer.css");
</style>

// src/app/footer/footer.component.ts
import { Component } from "@angular/core";

@Component({
  selector: "footer-comp",
  template: `<footer>
    <a
      href="https://loki87by.github.io/portfolio/"
      rel="noopener noreferrer"
      target="_blank"
    >
      &copy; 2022 Алексей Акулич
    </a>
  </footer>`,
  styleUrls: ["./footer.component.css"],
})
export class FooterComponent {}
